apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # type: LoadBalancer
  #   LoadBalancer: automatically create an "external" load-balanced IP for the frontend service.
  type: NodePort
  #   NodePort allows to expose the service in a internal port that are shared across the entire cluster.
  ports:
  # the port that this service should serve on
  - port: 80
    nodePort: 30080
  selector:
    app: guestbook
    tier: frontend
